import os
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

out_dir = r"g:\HACKATHON_PROJECTS\SEBI_GFF_CHANAKYA\Chanakya\frontend\apps\web\public\docs\demo"
os.makedirs(out_dir, exist_ok=True)

def generate_receipt():
    path = os.path.join(out_dir, "Shopping_Receipt.pdf")
    c = canvas.Canvas(path, pagesize=letter)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(200, 750, "Grocery Receipt")
    c.setFont("Helvetica", 12)
    c.drawString(100, 700, "Apples ............... $2.99")
    c.drawString(100, 680, "Bananas ............. $1.50")
    c.drawString(100, 660, "Milk ................... $3.49")
    c.drawString(100, 640, "Bread ................. $2.49")
    c.setFont("Helvetica-Bold", 12)
    c.drawString(100, 600, "Total ................. $10.47")
    
    # Watermark
    c.setFont("Helvetica-Oblique", 14)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(100, 100, "Generated by Gemini Nano Banana Model")
    c.save()

def generate_marksheet():
    path = os.path.join(out_dir, "College_Marksheet.pdf")
    c = canvas.Canvas(path, pagesize=letter)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(200, 750, "College Marksheet")
    c.setFont("Helvetica", 12)
    c.drawString(100, 700, "Student Name: John Doe")
    c.drawString(100, 680, "Student ID: 987654321")
    c.drawString(100, 650, "Subject 1: Mathematics - A")
    c.drawString(100, 630, "Subject 2: Physics - B+")
    c.drawString(100, 610, "Subject 3: Chemistry - A-")
    c.drawString(100, 590, "Subject 4: Literature - B")
    
    # Watermark
    c.setFont("Helvetica-Oblique", 14)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(100, 100, "Generated by Gemini Nano Banana Model")
    c.save()

generate_receipt()
generate_marksheet()
print("PDFs generated successfully.")
